<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <img src="/img/twitter_logo.png" />
        </div>

        <div class="row">
          <div class="col">

          <?php if(!$this->view->erroCadastro) { ?>

            <h2>Cadastro realizado com sucesso</h2>
            
          <?php } else { ?>
              
            <h2>Este usuário já está cadastrado</h2>

          <?php } ?>
          </div>
        </div>

        <div class="row">
          <div class="col">
            <a href="/" class="btn btn-primary btn-block">Clique aqui para fazer login!</a>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>



    
  